apiVersion: v1
kind: Service
metadata:
  name: {{ include "apollo-agent-minio.fullname" . }}-apollo-agent
  labels:
    {{- include "apollo-agent-minio.apollo-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apolloAgent.service.type }}
  {{- if eq .Values.apolloAgent.service.type "NodePort" }}
  ports:
  - port: {{ .Values.apolloAgent.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if .Values.apolloAgent.service.nodePort }}
    nodePort: {{ .Values.apolloAgent.service.nodePort }}
    {{- end }}
  {{- else }}
  ports:
  - port: {{ .Values.apolloAgent.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  {{- end }}
  selector:
    {{- include "apollo-agent-minio.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: apollo-agent

