apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apollo-agent-minio.fullname" . }}-minio
  labels:
    {{- include "apollo-agent-minio.labels" . | nindent 4 }}
type: Opaque
stringData:
  root-user: {{ .Values.minio.rootUser }}
  root-password: {{ .Values.minio.rootPassword }}

