apiVersion: v1
kind: Service
metadata:
  name: {{ include "apollo-agent-minio.fullname" . }}-minio
  labels:
    {{- include "apollo-agent-minio.minio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.minio.service.type }}
  ports:
  - port: {{ .Values.minio.service.apiPort }}
    targetPort: api
    protocol: TCP
    name: api
  - port: {{ .Values.minio.service.consolePort }}
    targetPort: console
    protocol: TCP
    name: console
  selector:
    {{- include "apollo-agent-minio.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: minio

